# This is a basic workflow that is manually triggered

name: Manual workflow Discord

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 終了後に discordのwebhookで通知を行う
    - name: Notify Discord
      run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "メッセージを送る！https://back-to-back.vercel.app/"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}